### ISSUE TITLE
Discount not working

### ISSUE THREAD

**Issue by titocalabrese** [Prospress/woocommerce-subscribe-to-all-the-things#11]
Don't know if it's only my case but when I try to add a percentage discount to product I receive a message on the product page that says that it is not possible to buy the product

**Comment by franticpsyx** [comment]
Hi @titocalabrese - How is discount being applied? Are you applying a coupon in the cart?

**Comment by titocalabrese** [comment]
Hi Manos,

I'm talking about the feature provided by this wonderful plugin (please
take a look to the attached image Discount.png).

If I try to add a discount (e.g. 5) I receive a message on the shop page
that prevent me from proceeding with the buying process (please take a look
to the second image in attachment Issue.png).

Let me know if you need further clarifications or any kind of support from
my side.

Have a nice day

Ciao, Tito

**Comment by titocalabrese** [comment]
Hi Manos,
I've checked better and I've understood that the issue is related to the composite product plugin. Sorry for my misunderstanding.

I was confused by Amazon pricing strategy that allows for a discount in case you subscribe to the product instead of just buying it only once.

Have a nice day,

Tito
