### ISSUE TITLE
Add price to subscription

### ISSUE THREAD

**Issue by jakeperrin** [Prospress/woocommerce-subscribe-to-all-the-things#14]
It would be nice to change the price for each subscription you add.

**Comment by seb86** [comment]
@jakeperrin Read [this discussion](https://github.com/Prospress/woocommerce-subscribe-to-all-the-things/pull/13) for my pull request.

**Comment by franticpsyx** [comment]
Duplicate of https://github.com/Prospress/woocommerce-subscribe-to-all-the-things/pull/13 - closing
