### ISSUE TITLE
Question for using Product Bundles & Subscribe to All the Things

### ISSUE THREAD

**Issue by samstone87** [Prospress/woocommerce-subscribe-to-all-the-things#17]
First off, apologies if this is not the right place to post this/ask this. Not familiar with proper GitHub etiquette :)

Currently using Product Bundles and Subscribe to All the Things on a staging site. Right now one of my set up goes like this 4 week subscription, 5% discount, and you get to choose from a variety of meal choices to make up your bundle. 

I don't know if this is possible already and I'm missing something (entirely the likely scenario) , but when I log in as the customer who has placed this subscription, my only option is to "cancel" the subscription in "my account". What I would like to do is change the meal types that make up my product bundle, and even increase the quantity as well, without having to cancel the whole thing (and of course raise/lower the price the customer would be billed every month). 

Is this possible already?

Thank you in advance!

**Comment by franticpsyx** [comment]
Hi @samstone87 - thanks for the feedback!

You are right that this isn't possible at the moment. WC Subscriptions only supports subscription switching for Variable / Grouped products, but we would like to extend that to support:

- subscriptions schemes switching
- changing the subscribed content of product types such as Bundles and Composites.

We already have an issue opened for all this here - https://github.com/Prospress/woocommerce-subscribe-to-all-the-things/issues/12
