### ISSUE TITLE
Ability to override recurring price with every defined subscription option

### ISSUE THREAD

**Issue by franticpsyx** [Prospress/woocommerce-subscribe-to-all-the-things#18]
Ref: #13

**Comment by furchildpets** [comment]
@franticpsyx Hi. I just wanted to let you know that I downloaded and tested your latest version -- ability to override product price. it worked for me a few times and then nothing. I can't get any of the combinations to work. It always defaults to the original price, even though when I look in the cart page the correct subscription and price are selected.  However, it either shows the original price or 0.00 for the total.

Any ideas?

Thanks

**Comment by franticpsyx** [comment]
@furchildpets Not sure which branch you were looking at, but there was no stable latest version with this feature in it until now.

Feel free to download and test the https://github.com/Prospress/woocommerce-subscribe-to-all-the-things/tree/issue-13-patches branch :)

**Comment by furchildpets** [comment]
@franticpsyx YEAH!!!! ;) It is working fantastically!! The mini cart is updating correctly and the 1 second delay with the WC Hover Cart plugin has gone away as well.

I have tested it with only Override Product Price with both Reg Price and Sale Price variations.  

Works great!!! Thank you so much.

![image](https://cloud.githubusercontent.com/assets/16845980/12771941/6fbc0f22-ca2d-11e5-9292-23cebe7b819c.png)

![image](https://cloud.githubusercontent.com/assets/16845980/12771945/81ac971a-ca2d-11e5-9de5-3b52a2d185cf.png)
