### ISSUE TITLE
No Subscription tab for variable products?

### ISSUE THREAD

**Issue by nbyloff** [Prospress/woocommerce-subscribe-to-all-the-things#21]
I am using Composite products to bundle a bunch of variable products together. On our staging site, trying to use this plugin with subscriptions & composite products. The readme says to create a simple/variable product then go to the subscriptions tab on that product.

I see it for the Simple product, but even after I save a variable product and add attributes, etc. I still don't see the subscriptions tab?

My end result is to try and attach a variable subscription to a composite product. Seeing if this will work for me since I need to force a subscription with a composite product purchase.

**Comment by franticpsyx** [comment]
>My end result is to try and attach a variable subscription to a composite product

Why not create a Composite product and then go to the Subscriptions tab to add Subscription plans?

The current version does not support Variable products - that's on my to-do list, though :)

**Comment by nbyloff** [comment]
That could work, but there is multiple variations of a subscription. There's plans for product A and plans for product B. So if you get a subscription for product A, you need to either choose basic, premiere, or corporate. Same for product subscription B, but they could be different choices for that one too. 

I think what I might do until variable products are supported is just force a redirect to a subscription page, and not let the user go to their cart until they've added a proper subscription.

**Comment by franticpsyx** [comment]
@nbyloff 

Just a note - variable products support has not been planned in detail - we could make it possible to add subscription plans at variable product level, or at variation level. Not sure which would work for your particular use case.

Also, products with SATT subscriptions in Composites is a matter that has not been studied in detail and is unlikely to be supported fully.

**Comment by nbyloff** [comment]
@franticpsyx 

Noted. At this point, being able to add a variable subscription at the product level would be sufficient for my purposes I think. 

What I am testing is a monitoring/electronic product that can come with multiple accessories. Something you can attach to equipment, and it sends a ping either through GPS or cell towers of it's current location. So composite product would work like this:

Composite product page is the actual device. Step 1 is accessories. Step 2 is extended warranty, Step 3 is the subscription type and will be one of two choices: GPS or cell tower service. The variations under each subscription is how many times a day you want the device to report its location.

So I would make one component for Reporting Types, add the two types of variable subscriptions (GPS or cell tower). 

If something like this won't be supported or planned for in the future, I'd like to contribute where I can, but wouldn't know where to start or what hooks I'd need to focus on.

**Comment by franticpsyx** [comment]
>Noted. At this point, being able to add a variable subscription at the product level would be sufficient for my purposes I think.

This is probably where we'll start - leave the variations functionality for product-related features, and use SATT to attach sub plans - same as with all other product types :)

**Comment by louis2b** [comment]
Hi there, 
Sub plans at product level for variation products is also exactly what I would need .
With your existing discount option for sub plans we would be able to use the variation levels prices and add a discount depending on the frequency of subscription. 
Thanks for your work !

**Comment by jmfonseca** [comment]
Yap, same thing here, For me it would work a subscription at the product level.

Also, it would be good to chose from a dropdown list or an option like Autoship does.

Use cases would be, if you have a bunch of subscription options it would be better to have a dropdown list.

When do you expect to have this figured out?

PS. THANK YOU SO MUCH FOR THIS EXTENTION.

**Comment by franticpsyx** [comment]
ref: #2
