### ISSUE TITLE
Discount for subscription not working?

### ISSUE THREAD

**Issue by samstone87** [Prospress/woocommerce-subscribe-to-all-the-things#22]
Hi,

I have successfully built a few subscriptions on my staging site, using Subscriptions, Product Bundles, Tabular Layout and Min/Max and here it's working and show the discount:

https://staging.doyoueveneatbro.com/product/subscription-test-2/

I copied the same thing when making a new type of subscription to be everyday and no matter what I put in the discount field (and I've made sure everything else is the same as the 3 other successful ones I built) I cannot get it to show a discount. 

https://staging.doyoueveneatbro.com/product/every-day-testing-subscription-renewal/

And the successful ones I built, don't show any number in the discount field anymore. Very confused on what I'm doing differently/incorrectly. 

Thanks in advance for your help!

**Comment by franticpsyx** [comment]
Discounts do not work with per-item priced Bundles yet :) there is already an open issue: https://github.com/Prospress/woocommerce-subscribe-to-all-the-things/issues/20

**Comment by samstone87** [comment]
Ah I see, just read that thread. Still so confused though. 

Do you know why I'm seeing a crossed out sale price and then when I rebuilt it as another subscription product it doesn't have a crossed out sale price?

 Looking at them side-by-side I copied the same details when building this one (https://staging.doyoueveneatbro.com/product/every-day-testing-subscription-renewal/) but I can't get that discount price to show up or see where I put that in at, seemed so intuitive when I built this one first a few weeks ago (https://staging.doyoueveneatbro.com/product/subscription-test-2/)
