### ISSUE TITLE
What is the best way to integrate with other Product Plugins?

### ISSUE THREAD

**Issue by furchildpets** [Prospress/woocommerce-subscribe-to-all-the-things#23]
Hello,

We are using WooCommerce Custom Product Boxes by Wsdom Labs to create assorted product boxes that clients can fill with any combination of Simple Products.

https://wisdmlabs.com/assorted-bundles-woocommerce-custom-product-boxes-plugin/

![image](https://cloud.githubusercontent.com/assets/16845980/12982896/36756658-d0e7-11e5-87ad-bb921b8e8d9d.png)

![image](https://cloud.githubusercontent.com/assets/16845980/12982901/3f71b93c-d0e7-11e5-9778-58fbe6062f08.png)

How do we get Subscribe to Anything to recognize / register this custom product type?

Thanks,

fcp

**Comment by franticpsyx** [comment]
@furchildpets No plans to integrate 3rd party products at the moment :) Once we manage to integrate with the most popular WooThemes product extensions, we can start looking into 3rd party product types.

**Comment by furchildpets** [comment]
Ok understood. I will have the plugin developer look at your git project and maybe we will create a fork and see what we can do on our own.

I just hoping that there might be some standard action, functions to use when registering a new product type.

Thanks again!!!
