### ISSUE TITLE
Subscription options on Composite Product

### ISSUE THREAD

**Issue by glagonikas** [Prospress/woocommerce-subscribe-to-all-the-things#24]
Hi,

When i try to add a second subscription option on a Composite Product, the front-end displays an unordered list instead of a dropdown.

Thanks

WP: 4.4.2
WooCommerce: 2.5.2
WooCommerce Composite Products: 3.5.4
WooCommerce Subscribe All the Things: 1.0.2
WooCommerce Subscriptions: 2.0.9

**Comment by franticpsyx** [comment]
Hi George,

Unless I am missing something, that's the default behaviour (radio buttons, not dropdown).

**Comment by glagonikas** [comment]
Hi Manos,

Sorry, i probably didn't explain myself properly on this one... It displays a <UL> element. So something like
- Item 1
- Item 2

which doesn't allow you to pick an option.

**Comment by glagonikas** [comment]
After some further testing, i noticed that's probably caused from the Salient theme 7.0.6. Switching back to twentysixteen displays the radio buttons.

The code is

`<ul class="wcsatt-convert-product">
    <li>
        <label>
            <input type="radio" checked="checked" value="1_month_0" name="convert_to_sub_545">
            Every month
        </label>
    </li>
    <li>
        <label>
            <input type="radio" value="2_month_0" name="convert_to_sub_545">
            Every 2 months
        </label>
    </li>
    <li>
        <label>
            <input type="radio" value="3_month_0" name="convert_to_sub_545">
            Every 3 months
        </label>
    </li>
</ul>
`

so the radio buttons are indeed in place

![screenshot-2016-02-24 09-41-38](https://cloud.githubusercontent.com/assets/10516403/13281407/952bc626-dadb-11e5-8b04-aa9df81b343c.png)
.

I'm not sure if that's something you need to fix or the theme owner?

Thanks
