### ISSUE TITLE
Composite Product Discounts & Free Shipping Options

### ISSUE THREAD

**Issue by kirillminiaev** [Prospress/woocommerce-subscribe-to-all-the-things#33]
Based on my experiments and research, it seems that as of right now, this plugin does not support subscription discounts on variable products that are subordinate to a composite product. Is that correct? Every time I try to change the price for various subscription time-periods for the child variable product, the plugin does not recognize the price difference (be it a % difference or a static "Override Product" price difference).

Also, is there any plan or thought process around offering a "Free Shipping" toggle for any product that is bought with subscription?

**Comment by franticpsyx** [comment]
@kirillminiaev StATT is untested for this use case.

Composite products support is limited to attaching Subscription options at Composite product level.

If you have attached Subscription schemes to any product that is part of a Composite, things may not work as expected.

We are planning to look into this and address it as part of implementing full support for complex product types.

>Also, is there any plan or thought process around offering a "Free Shipping" toggle for any product that is bought with subscription?

Unfortunately, not. This is definitely custom-coding area and beyond the scope of StATT.

**Comment by kirillminiaev** [comment]
@franticpsyx Thank you for your response. The subscription options were attached at the Composite product level. My apologies if this wasn't clear from my original message.

Re: Free Shipping, understood. Will consider workarounds.

**Comment by franticpsyx** [comment]
>The subscription options were attached at the Composite product level.

Possibly related: https://github.com/Prospress/woocommerce-subscribe-to-all-the-things/issues/20 ?

**Comment by kirillminiaev** [comment]
@franticpsyx That's what I figured. Any updates on the 1.1 milestone? I will wait for it.

**Comment by franticpsyx** [comment]
Hard to say. All issues added to the 1.1 milestone (https://github.com/Prospress/woocommerce-subscribe-to-all-the-things/milestones/1.1) are quite complex and the resources we can dedicate to StATT development at the moment are more limited than we'd like.
