### ISSUE TITLE
Error on plugin activation

### ISSUE THREAD

**Issue by geekjoy** [Prospress/woocommerce-subscribe-to-all-the-things#9]
First off i'm using your WC Subscriptions plugin on Wordpress 4.3.1 and Subscribe to all things 1.0.1. As soon as I activate the plugin and the page refreshes to show activation success, I get this error,

> Fatal error: Can't use function return value in write context in /home/cafecartel/public_html/wp-content/plugins/woocommerce-subscribe-to-all-the-things-1.0.1/includes/class-wcsatt-display.php on line 161

I'm trying to put together a subscription based site for physical coffee products and i'm lost with this. I'm also using Composite Products and Product Bundles extensions if that matters.

**Comment by geekjoy** [comment]
Just tried version 1.0.2 from the master, and that had the same error.

**Comment by franticpsyx** [comment]
@geekjoy Thanks for reporting this. Can you re-download the master branch and re-test? Also, you might consider updating your php version ;)

**Comment by geekjoy** [comment]
@franticpsyx I just re-downloaded the master, no more errors on activation. Everything seems to work now, thanks for the fix. I would consider updating the php version, but its a client server and they just want to control that themselves.

**Comment by franticpsyx** [comment]
Good to know, thanks!
